[colors]
transparent_background_colors = true

[colors.normal]
white = "#f7f7f7"

[colors.primary]
background = "#212b30"
foreground = "#f7f7f7"

[font]
builtin_box_drawing = true
size = 0.5

[font.normal]
family = "Fira Code"

[scrolling]
history = 0

[terminal.shell]
program = "/home/vix/opt/den/bin/catnip-alacritty.sh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = false
opacity = 0.0
resize_increments = true
title = "Catnip Visualizer"

[window.class]
general = "Catnip Visualizer"
instance = "Catnip Visualizer"

[window.dimensions]
columns = 2496
lines = 60

[window.position]
x = 1472
y = 1674
